//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.DE_ORDER = new HashSet<DE_ORDER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string AVATAR { get; set; }
        public int QUANTITY { get; set; }
        public int PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE { get; set; }
        public string CATEGORYNAME { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEAT { get; set; }
        public Nullable<int> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEAT { get; set; }
        public Nullable<int> IDCATEGORY { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_ORDER> DE_ORDER { get; set; }
    }
}
